### ISSUE TITLE
Update plan

### ISSUE THREAD

**Issue by marocchino** [ruby-korea/bundler-site#10]
- [x] 1.5 문서 업데이트
- 1.9 버전 번역
  - [x] bundle_binstubs
  - [x] bundle_check
  - [x] bundle_clean
  - [x] bundle_config
  - [x] bundle_console
  - [x] bundle_exec
  - [x] bundle_gem
  - [x] bundle_help
  - [x] bundle_init
  - [x] bundle_inject
  - [x] bundle_install
  - [x] bundle_open
  - [x] bundle_outdated
  - [x] bundle_package
  - [x] bundle_platform
  - [x] bundle_show
  - [x] bundle_update
  - [x] bundle_version
  - [x] bundle_viz
  - [x] bundler_setup
  - [x] bundler_sharing
  - [x] bundler_workflow
  - [x] commands
  - [x] deploying
  - [x] faq
  - [x] gemfile
  - [x] gemfile_ruby
  - [x] git
  - [x] groups
  - [x] index
  - [x] rails23
  - [x] rails3
  - [x] rationale
  - [x] rubygems
  - [x] rubymotion
  - [x] sinatra
  - [x] updating_gems
  - [x] whats_new

- ~~한국어 문서 폴더 변경~~

**Comment by marocchino** [comment]
마스터 브랜치와 머지했습니다.

**Comment by marocchino** [comment]
잘모르는 미들맨이라 폴더는 변경하기 힘드네요 -ㅅ-;
일단 그대로 두겠습니다.

**Comment by yous** [comment]
:+1:

**Comment by marocchino** [comment]
@yous 수고하셨어요. :)
