### ISSUE TITLE
link 문제

### ISSUE THREAD

**Issue by marocchino** [ruby-korea/bundler-site#20]
http_prefix가 적용안되 링크가 잘못된 곳을 보고있는 곳이 있습니다.

- http://ruby-korea.github.io/#getting-started
- http://ruby-korea.github.io/v1.9/man/bundle.1.html
- http://ruby-korea.github.io/#get-involved
- http://ruby-korea.github.io/blog/

**Comment by yous** [comment]
어디에서 걸린 링크인지는 알 수 없는 건가요?

**Comment by marocchino** [comment]
일단은 source/partials/_sidebar.haml입니다만 다른곳에서도 비슷하게 링크가 걸려있으면 링크가 깨질 우려가 있습니다.

**Comment by yous** [comment]
일단 `link_to` 태그가 쓰인 곳부터 확인해봐야 할 것 같네요.

**Comment by marocchino** [comment]
으으 -_-;; 
http://ruby-korea.github.io/bundler-site/ 링크 누를 때마다 두근두근하네요.
